import Image from 'next/image'
import Head from 'next/head'
import Header from '@/components/Header'

export default function Home() {
  return (
    <>
    <Head>
        <title>Prasham  Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className="bg-gray-100 min-h-screen">
     <Header/>
    </main></>
    
  )
}
